// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTYXdtxivH4ufTNOgKblY9qu3c2eJ7-2s',
    appId: '1:847664048188:web:adf7291dd553efa17cfb39',
    messagingSenderId: '847664048188',
    projectId: 'employee-info-cd965',
    authDomain: 'employee-info-cd965.firebaseapp.com',
    storageBucket: 'employee-info-cd965.appspot.com',
    measurementId: 'G-8J9126CCK1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQOon0YcBgyO0oVYgD3Wr0XdD4oKZhOLw',
    appId: '1:847664048188:android:721da3b65cda80437cfb39',
    messagingSenderId: '847664048188',
    projectId: 'employee-info-cd965',
    storageBucket: 'employee-info-cd965.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCy2piFIFFFWukbgcuY_f6b-ww7GldDTJ0',
    appId: '1:847664048188:ios:95c2e705d8e8faa87cfb39',
    messagingSenderId: '847664048188',
    projectId: 'employee-info-cd965',
    storageBucket: 'employee-info-cd965.appspot.com',
    iosClientId: '847664048188-g7pvactgm1uv03t0mao9cd07nao22kd3.apps.googleusercontent.com',
    iosBundleId: 'com.example.employeeInfo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCy2piFIFFFWukbgcuY_f6b-ww7GldDTJ0',
    appId: '1:847664048188:ios:95c2e705d8e8faa87cfb39',
    messagingSenderId: '847664048188',
    projectId: 'employee-info-cd965',
    storageBucket: 'employee-info-cd965.appspot.com',
    iosClientId: '847664048188-g7pvactgm1uv03t0mao9cd07nao22kd3.apps.googleusercontent.com',
    iosBundleId: 'com.example.employeeInfo',
  );
}
